export const courseReviews = {
  makeup: [
    "I learned professional bridal makeup techniques with complete practical training.",
    "The makeup course helped me understand HD makeup and modern beauty techniques.",
    "I gained detailed knowledge about bridal makeup, party makeup, and professional looks.",
    "The practical makeup sessions improved my creativity and confidence.",
    "I learned how to create flawless makeup looks for different occasions.",
    "The HD makeup training was very detailed and easy to understand.",
    "I gained hands-on experience in professional makeup applications.",
    "The bridal makeup techniques taught here are modern and industry-focused.",
    "I learned everything from basic makeup to advanced professional techniques.",
    "The makeup course gave me confidence to work with real clients.",
    "I improved my skills in creating natural and glamorous makeup looks.",
    "The practical classes helped me understand every makeup product and its use.",
    "I learned professional skin preparation and makeup application methods.",
    "The makeup training covered all important techniques required for a beauty career.",
    "I developed advanced skills in bridal makeup and professional beauty services.",
    "The course helped me understand different face shapes and suitable makeup styles.",
    "I learned modern makeup trends and latest beauty techniques.",
    "The practical sessions made learning makeup simple and enjoyable.",
    "I gained confidence in handling bridal and party makeup clients.",
    "The training provided complete knowledge about professional makeup services.",
    "I learned advanced blending, contouring, and highlighting techniques.",
    "The makeup classes focused on practical learning and real salon experience.",
    "I received excellent guidance for creating long-lasting bridal makeup looks.",
    "The course improved my creativity and professional makeup skills.",
    "I learned the correct use of professional makeup tools and products.",
    "The academy provided detailed training in HD and bridal makeup.",
    "I gained valuable experience through regular practical makeup sessions.",
    "The makeup course helped me turn my passion into a professional skill.",
    "I learned how to achieve perfect finishing in professional makeup.",
    "The classes covered modern makeup styles and advanced techniques.",
    "I developed confidence in performing makeup services independently.",
    "The training included complete knowledge of professional makeup procedures.",
    "I learned every step of a professional makeup process in detail.",
    "The course provided practical exposure to real beauty industry standards.",
    "I gained expertise in creating elegant bridal and party makeup looks.",
    "The makeup training improved my understanding of color combinations.",
    "I learned how to select suitable makeup according to skin types.",
    "The practical approach made advanced makeup techniques easy to learn.",
    "The course helped me become more creative as a makeup artist.",
    "I gained professional knowledge about makeup products and their applications.",
    "The academy taught me modern bridal makeup styles and techniques.",
    "I learned advanced eye makeup and face enhancement techniques.",
    "The training helped me understand professional client requirements.",
    "I gained confidence in providing high-quality makeup services.",
    "The practical sessions improved my speed and perfection in makeup.",
    "I learned how to create camera-friendly HD makeup looks.",
    "The course provided complete knowledge of professional beauty standards.",
    "I developed skills required to become a successful makeup artist.",
    "The makeup training was highly practical and career-oriented.",
    "I learned techniques used by professional makeup artists in the beauty industry.",
        "I learned advanced bridal makeup techniques with professional practical guidance.",
    "The makeup course helped me master flawless makeup application and finishing techniques.",
    "I gained confidence in creating beautiful looks suitable for different occasions.",
    "The training improved my understanding of professional makeup standards and trends.",
    "I learned the secrets of perfect base makeup, blending, and smooth finishing.",
    "The practical sessions helped me develop creativity and attention to every detail.",
    "I gained hands-on experience in creating bridal, party, and glamorous makeup looks.",
    "The course provided detailed knowledge about modern beauty products and their uses.",
    "I learned professional makeup techniques that are used by expert makeup artists.",
    "The training helped me understand client requirements and suitable makeup styles.",
    
    "I gained confidence to work independently as a professional makeup artist.",
    "The practical classes improved my speed, precision, and makeup skills.",
    "I learned how to achieve natural, elegant, and high-definition makeup looks.",
    "The course provided complete practical exposure to professional makeup services.",
    "I gained knowledge about selecting the right products according to skin types.",
    "The academy provided excellent guidance for learning modern bridal makeup styles.",
    "I learned advanced techniques of contouring, highlighting, and face enhancement.",
    "The training improved my confidence in handling bridal makeup clients.",
    "The practical learning environment made every makeup technique easy to understand.",
    "I developed professional skills required to succeed in the makeup industry.",
    
    "The course helped me understand the latest makeup trends and beauty standards.",
    "I learned professional eye makeup techniques including smokey and glamorous looks.",
    "The practical sessions provided real experience of working like a professional makeup artist.",
    "I gained expertise in creating customized makeup looks for different clients.",
    "The training focused on both creativity and technical skills in makeup artistry.",
    "I learned how to maintain hygiene and professionalism during makeup services.",
    "The academy provided complete support to improve my makeup techniques.",
    "The practical classes helped me become more confident and skilled every day.",
    "I gained valuable experience through regular makeup practice and demonstrations.",
    "The course helped me transform my creativity into professional makeup expertise.",
    
    "I learned modern bridal makeup trends that are highly demanded in the beauty industry.",
    "The training provided excellent knowledge of HD makeup and long-lasting techniques.",
    "I gained practical experience in creating camera-ready and flawless makeup looks.",
    "The course taught me professional methods of skin preparation before makeup.",
    "I learned how to create balanced makeup according to face features and occasions.",
    "The practical sessions improved my ability to deliver high-quality makeup services.",
    "I gained confidence to start my journey as a freelance makeup artist.",
    "The academy helped me understand professional client consultation and service quality.",
    "I learned complete makeup procedures from preparation to final touch-ups.",
    "The training provided a perfect balance of theoretical knowledge and practical experience.",
    
    "I developed strong skills in professional makeup application and finishing.",
    "The course helped me become more creative and confident as a makeup artist.",
    "I learned advanced beauty techniques that enhanced my professional abilities.",
    "The practical classes were informative, detailed, and focused on real salon work.",
    "I gained professional knowledge about different makeup products and tools.",
    "The academy provided a supportive environment for improving my makeup talent.",
    "I learned techniques to create elegant bridal and special occasion makeup.",
    "The makeup training was career-oriented, practical, and easy to understand.",
    "I gained valuable skills to provide professional makeup services confidently.",
    "I highly appreciate the expert guidance and practical makeup training received during the course."

  ],


  nail: [
  "I learned professional nail extension techniques with complete practical training.",
  "The nail extension course helped me understand modern nail art and designs.",
  "I gained hands-on experience in professional nail extension services.",
  "The practical nail classes improved my creativity and confidence.",
  "I learned how to create beautiful and long-lasting nail extensions.",
  "The course provided complete knowledge about different nail extension methods.",
  "I gained professional skills in nail art, shaping, and finishing techniques.",
  "The training helped me understand proper nail preparation and hygiene standards.",
  "I learned advanced nail designs and trending nail art techniques.",
  "The practical sessions made learning nail extension easy and enjoyable.",
  "I gained confidence in providing professional nail services to clients.",
  "The nail extension training covered all essential salon techniques.",
  "I learned the correct use of professional nail tools and products.",
  "The course helped me transform my interest in nails into a professional skill.",
  "I gained practical knowledge of gel nails and modern nail techniques.",
  "The training improved my precision and creativity in nail designing.",
  "I learned different styles of nail art suitable for various occasions.",
  "The practical classes provided real salon experience and confidence.",
  "I developed professional skills required to become a successful nail artist.",
  "The course included detailed training in nail extension application and removal.",
  "I learned professional methods of nail care and maintenance.",
  "The academy provided excellent practical guidance throughout the training.",
  "I gained expertise in creating stylish and attractive nail designs.",
  "The nail extension course improved my confidence to work independently.",
  "I learned modern nail trends and professional beauty standards.",
  "The practical sessions helped me achieve perfection in nail services.",
  "I gained complete knowledge about nail extension products and their applications.",
  "The training provided detailed understanding of professional nail techniques.",
  "I learned how to customize nail designs according to client preferences.",
  "The course helped me start my journey as a professional nail artist.",
  "I developed confidence in handling nail extension clients professionally.",
  "The academy taught me advanced techniques of nail enhancement and decoration.",
  "I learned complete nail extension procedures from preparation to final finishing.",
  "The practical approach made every nail technique simple to understand.",
  "I gained professional knowledge about nail health and hygiene practices.",
  "The training improved my speed and accuracy in nail extension services.",
  "I learned creative nail art techniques using modern tools and materials.",
  "The course provided excellent exposure to professional salon nail services.",
  "I gained confidence in creating trendy and elegant nail designs.",
  "The practical classes helped me improve my artistic skills and creativity.",
  "I learned advanced techniques for beautiful and durable nail extensions.",
  "The training provided complete knowledge of salon-level nail services.",
  "I developed professional skills in nail shaping and design techniques.",
  "The course helped me understand the latest nail industry trends.",
  "I gained hands-on experience in various nail extension styles.",
  "The academy provided a supportive environment for learning nail art.",
  "I learned professional techniques for maintaining high-quality nail services.",
  "The practical sessions made me more confident in my nail artistry.",
  "The training covered both basic and advanced nail extension methods.",
  "I gained valuable experience through regular nail practice sessions.",

  "I learned how to create customized nail designs for different clients.",
  "The course provided complete practical exposure to professional nail services.",
  "I developed confidence to work as a professional nail technician.",
  "The training helped me understand client requirements and nail preferences.",
  "I gained excellent knowledge about modern nail extension techniques.",
  "The academy taught me professional salon standards and work ethics.",
  "I learned proper methods of nail cleaning, shaping, and finishing.",
  "The practical classes improved my attention to detail and creativity.",
  "The nail extension course gave me the confidence to start my career.",
  "I gained expertise in creating premium quality nail extension looks.",
  "The training provided detailed knowledge of nail products and equipment.",
  "I learned professional methods for achieving perfect nail finishing.",
  "The practical sessions helped me become more skilled and efficient.",
  "The course enhanced my creativity in designing unique nail patterns.",
  "I gained confidence in providing attractive nail art services.",
  "The academy provided high-quality nail training with expert guidance.",
  "I learned advanced techniques used by professional nail artists.",
  "The training helped me understand the importance of nail hygiene.",
  "I developed skills required to build a successful career in nail artistry.",
  "The practical learning experience was informative and career-focused.",
  "I learned how to create elegant bridal and party nail designs.",
  "The course provided a strong foundation in professional nail services.",
  "I gained practical experience in different nail extension applications.",
  "The training improved my knowledge of beauty and nail trends.",
  "I developed confidence to handle professional nail clients independently.",
  "The academy helped me improve my creativity and technical skills.",
  "I learned complete nail extension techniques with professional guidance.",
  "The practical classes helped me achieve better finishing and quality.",
  "The course provided excellent knowledge about modern nail art styles.",
  "I gained professional experience in salon-style nail treatments.",
  "The training helped me understand advanced nail enhancement procedures.",
  "I learned techniques to create fashionable and attractive nail looks.",
  "The academy provided detailed practical training and personal attention.",
  "I developed confidence through regular hands-on nail practice.",
  "The course helped me become skilled in professional nail artistry.",
  "I gained complete understanding of nail extension safety and care.",
  "The practical sessions improved my overall performance as a nail artist.",
  "I learned innovative nail techniques that are popular in the beauty industry.",
  "The training was well-structured, practical, and easy to understand.",
  "I gained valuable skills to provide professional nail services confidently.",
  "The academy helped me turn my passion for nail art into a successful career.",
  "The nail extension course provided excellent practical knowledge and professional exposure.",
  "I highly appreciate the professional training and supportive learning environment."
],

  skin: [
  "I learned professional facial techniques with complete practical training.",
  "The skin beautician course helped me understand advanced skincare treatments.",
  "I gained detailed knowledge about facials, cleanup, and skin analysis.",
  "The practical skincare sessions improved my confidence and professional skills.",
  "I learned how to provide personalized skincare treatments for different skin types.",
  "The facial training was detailed, practical, and easy to understand.",
  "I gained hands-on experience in professional beauty and skincare services.",
  "The skin course covered all essential techniques required for a successful beauty career.",
  "I learned professional methods of cleansing, exfoliation, and skin care.",
  "The practical classes helped me understand various beauty products and their uses.",
  "I gained confidence in providing professional facial and skin services.",
  "The training included complete knowledge of modern skincare techniques.",
  "I learned advanced facial massage techniques and professional beauty procedures.",
  "The course helped me understand different skin concerns and their treatments.",
  "I developed professional skills in skincare and salon services.",
  "The practical sessions made learning beauty treatments simple and enjoyable.",
  "I learned how to perform different types of facials professionally.",
  "The course provided complete practical exposure to salon skincare services.",
  "I gained valuable experience through regular hands-on beauty practice.",
  "The skin beautician training improved my confidence to work with clients.",
  "I learned professional cleanup techniques for healthy and glowing skin.",
  "The academy provided excellent knowledge about skin health and beauty care.",
  "I gained expertise in using professional skincare products correctly.",
  "The training helped me understand the importance of proper skin consultation.",
  "I learned advanced beauty techniques for maintaining healthy and radiant skin.",
  "The practical approach made professional skincare techniques easy to learn.",
  "I developed confidence in handling different skin types and concerns.",
  "The course covered complete beauty therapy and skincare procedures.",
  "I learned modern facial techniques used in professional beauty salons.",
  "The training provided detailed knowledge of skin treatments and care methods.",
  "I gained professional knowledge about skin hygiene and beauty standards.",
  "The practical classes improved my speed and perfection in skincare services.",
  "I learned how to deliver relaxing and effective facial treatments.",
  "The skin course helped me transform my passion into a professional skill.",
  "I gained confidence to provide beauty services independently.",
  "The academy taught me professional salon-level skincare techniques.",
  "I learned complete facial procedures from preparation to finishing.",
  "The practical sessions helped me understand real salon work experience.",
  "I developed advanced skills in beauty and skincare treatments.",
  "The training was highly practical and focused on professional development.",
  "I learned how to choose suitable skincare treatments according to skin needs.",
  "The course improved my knowledge about professional beauty services.",
  "I gained hands-on experience in various facial and skincare methods.",
  "The classes were well-organized with detailed practical demonstrations.",
  "I learned techniques to improve skin appearance and maintain skin health.",
  "The training provided complete guidance about professional beauty practices.",
  "I developed confidence in performing skincare services with perfection.",
  "The course helped me understand modern beauty trends and treatments.",
  "I learned advanced salon techniques for professional skin care.",
  "The practical learning environment made every session interesting.",
  "I gained complete knowledge of facial machines and their applications.",
  "The skin beautician course provided excellent career-oriented training.",
  "I learned professional methods of skin cleansing and rejuvenation.",
  "The academy helped me build strong practical skills in skincare.",
  "I gained valuable knowledge about different facial products and ingredients.",
  "The training improved my understanding of beauty and wellness services.",
  "I learned professional techniques for achieving healthy and glowing skin.",
  "The practical sessions increased my confidence in beauty treatments.",
  "The course helped me understand client needs and skin requirements.",
  "I learned how to maintain proper hygiene during beauty procedures.",
  "The training provided real salon experience with practical exposure.",
  "I gained confidence in performing advanced beauty services.",
  "The academy provided a perfect environment for learning skincare techniques.",
  "I learned complete professional skin treatment procedures.",
  "The course enhanced my creativity and confidence as a beauty professional.",
  "I gained practical knowledge of advanced facial therapies.",
  "The training covered both basic and advanced skin beautician techniques.",
  "I learned professional ways to improve client satisfaction in beauty services.",
  "The practical classes helped me achieve perfection in skincare treatments.",
  "I developed strong knowledge of modern beauty and skincare methods.",
  "The course gave me the confidence to start my beauty career.",
  "I learned professional salon techniques through detailed practical sessions.",
  "The academy helped me understand the latest skincare trends.",
  "I gained expertise in professional beauty treatments and services.",
  "The practical learning experience was very informative and beneficial.",
  "I learned how to provide customized skincare solutions for clients.",
  "The training improved my professional beauty skills significantly.",
  "I developed confidence to work as a professional skin beautician.",
  "The course provided complete knowledge of salon skincare standards.",
  "I learned advanced methods of facial therapy and skin care.",
  "The practical sessions helped me become more skilled and professional.",
  "I gained excellent knowledge about beauty treatments and client care.",
  "The academy provided high-quality training with personal attention.",
  "I learned professional techniques required for the beauty industry.",
  "The skin beautician course was detailed, practical, and career-focused.",
  "I gained the skills needed to provide professional skincare services.",
  "The training helped me become more confident in beauty treatments.",
  "I learned complete salon procedures with proper professional guidance.",
  "The practical sessions helped me improve my accuracy and techniques.",
  "The course provided a strong foundation for my beauty career.",
  "I gained professional experience in skincare and beauty services.",
  "The academy provided excellent practical training and expert guidance.",
  "I learned modern techniques used by professional skin beauticians.",
  "The training improved my understanding of beauty care and treatments.",
  "I developed confidence to handle clients professionally.",
  "The course gave me practical knowledge and professional expertise.",
  "I learned advanced beauty treatments in a friendly learning environment.",
  "The academy helped me achieve my dream of becoming a beauty professional.",
  "The skin beautician training provided me with valuable skills for my future career.",
  "I highly appreciate the practical training and professional guidance received during the course."
],

  hair: [
  "I learned professional hair styling techniques with complete practical training.",
  "The hair styling course helped me understand modern hairstyles and trends.",
  "I gained hands-on experience in creating beautiful and professional hairstyles.",
  "The practical hair classes improved my creativity and confidence.",
  "I learned different bridal hairstyles with perfect finishing techniques.",
  "The course provided complete knowledge about professional hair styling methods.",
  "I gained confidence in creating stylish hairstyles for different occasions.",
  "The training helped me understand modern salon hair styling techniques.",
  "I learned advanced hair styling with practical demonstrations and guidance.",
  "The practical sessions made learning hair styling easy and enjoyable.",
  "I gained professional skills required to become a successful hair stylist.",
  "The hair styling training covered all essential salon techniques.",
  "I learned the proper use of professional hair styling tools and equipment.",
  "The course helped me transform my passion for hairstyling into a professional skill.",
  "I gained practical knowledge of bridal and party hairstyles.",
  "The training improved my speed, creativity, and perfection in hairstyling.",
  "I learned different types of curls, waves, and elegant hair looks.",
  "The practical classes provided real salon experience and confidence.",
  "I developed professional skills in creating modern and traditional hairstyles.",
  "The course included detailed training from basic to advanced hair styling.",
  "I learned professional methods of hair sectioning and styling.",
  "The academy provided excellent practical guidance throughout the course.",
  "I gained expertise in creating trendy and fashionable hairstyles.",
  "The hair styling course improved my confidence to work independently.",
  "I learned the latest hair trends and professional beauty standards.",
  "The practical sessions helped me achieve perfection in hair styling services.",
  "I gained complete knowledge about hair styling products and their uses.",
  "The training provided detailed understanding of professional hair techniques.",
  "I learned how to create hairstyles according to different face shapes.",
  "The course helped me start my journey as a professional hair stylist.",
  "I developed confidence in handling hair styling clients professionally.",
  "The academy taught me advanced techniques of bridal and party hairstyles.",
  "I learned complete hair styling procedures from preparation to final finishing.",
  "The practical approach made every hair technique simple to understand.",
  "I gained professional knowledge about hair care and hygiene standards.",
  "The training improved my accuracy and creativity in hair styling services.",
  "I learned creative hairstyles using modern tools and professional techniques.",
  "The course provided excellent exposure to professional salon hair services.",
  "I gained confidence in creating elegant and trendy hair looks.",
  "The practical classes helped me improve my artistic skills and imagination.",
  "I learned advanced techniques for long-lasting and beautiful hairstyles.",
  "The training provided complete knowledge of salon-level hair styling services.",
  "I developed professional skills in hair finishing and styling techniques.",
  "The course helped me understand the latest trends in the hair industry.",
  "I gained hands-on experience in various bridal and fashion hairstyles.",
  "The academy provided a supportive environment for learning hairstyling.",
  "I learned professional techniques for maintaining quality in hair services.",
  "The practical sessions made me more confident in my hairstyling skills.",
  "The training covered both basic and advanced hair styling methods.",
  "I gained valuable experience through regular hair styling practice sessions.",

  "I learned how to create customized hairstyles according to client requirements.",
  "The course provided complete practical exposure to professional hair services.",
  "I developed confidence to work as a professional hair stylist.",
  "The training helped me understand client preferences and hairstyle selection.",
  "I gained excellent knowledge about modern hair styling techniques.",
  "The academy taught me professional salon standards and work ethics.",
  "I learned proper methods of hair preparation, styling, and finishing.",
  "The practical classes improved my attention to detail and creativity.",
  "The hair styling course gave me the confidence to start my career.",
  "I gained expertise in creating premium-quality hairstyles.",
  "The training provided detailed knowledge of hair products and styling equipment.",
  "I learned professional methods for achieving perfect hair finishing.",
  "The practical sessions helped me become more skilled and efficient.",
  "The course enhanced my creativity in designing unique hairstyles.",
  "I gained confidence in providing attractive hair styling services.",
  "The academy provided high-quality hair training with expert guidance.",
  "I learned advanced techniques used by professional hair stylists.",
  "The training helped me understand the importance of proper hair care.",
  "I developed skills required to build a successful career in hairstyling.",
  "The practical learning experience was informative and career-focused.",
  "I learned how to create elegant bridal hairstyles for weddings and events.",
  "The course provided a strong foundation in professional hair styling.",
  "I gained practical experience in different hairstyle creations.",
  "The training improved my knowledge of beauty and hair trends.",
  "I developed confidence to handle professional hair styling clients independently.",
  "The academy helped me improve my creativity and technical skills.",
  "I learned complete hair styling techniques with professional guidance.",
  "The practical classes helped me achieve better finishing and quality.",
  "The course provided excellent knowledge about modern hairstyle trends.",
  "I gained professional experience in salon-style hair treatments.",
  "The training helped me understand advanced hair styling procedures.",
  "I learned techniques to create fashionable and attractive hairstyles.",
  "The academy provided detailed practical training and personal attention.",
  "I developed confidence through regular hands-on hairstyling practice.",
  "The course helped me become skilled in professional hair artistry.",
  "I gained complete understanding of hair styling safety and care.",
  "The practical sessions improved my overall performance as a hair stylist.",
  "I learned innovative hairstyles that are popular in the beauty industry.",
  "The training was well-structured, practical, and easy to understand.",
  "I gained valuable skills to provide professional hair services confidently.",
  "The academy helped me turn my passion for hairstyling into a successful career.",
  "The hair styling course provided excellent practical knowledge and professional exposure.",
  "I highly appreciate the professional training and supportive learning environment.",
  "The hair styling classes helped me develop confidence and professional expertise.",
  "I learned creative bridal and party hairstyles with detailed practical sessions.",
  "The course gave me complete knowledge to begin my career as a hair stylist.",
  "The academy provided an excellent platform to learn professional hair styling."
]
};